### ISSUE TITLE
Help getting this plugin to work with 64-bit VMD for OSX Catalina

### ISSUE THREAD

**Issue by jennyfothergill** [mphoward/gsd-vmd#3]
Hi there, 
Thank you so much for making this plug-in! My lab uses it all the time. With OSX no longer supporting 32-bit apps some of us have switched to this version of VMD [https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/31208.html](https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/31208.html)
Do you have any advice for how to get your plug-in to work with this architecture?

**Comment by mphoward** [comment]
No problem! This might be a naive question, but have you tried compiling this plugin with this application, and if so, what outputs or errors are you getting? In principle, you would want to set `CMAKE_OSX_ARCHITECTURES=x86_64` for a 64-bit only build and then use any reasonable compiler that's compatible with your VMD. If the plugin is pointed at the right VMD app, it should install inside there and hopefully can be dynamically loaded. I'm not currently using VMD on OS X, though, so I've never tried myself.

To test this, could you modify this line:

https://github.com/mphoward/gsd-vmd/blob/c74357a7c0ce40028134869622eae7edde7ea4d5/CMakeLists.txt#L18

to remove `FORCE` and then set `CMAKE_OSX_ARCHITECTURES=x86_64` yourself?

**Comment by jennyfothergill** [comment]
Oh my gosh, thank you so much! Sorry I am a cmake noob, so I didn't know
how to fix it! :)

**Comment by mphoward** [comment]
Great, easy fixes are good! :-)

I will remove `FORCE` from that CMake line so that users have the option to choose to compile only `x86_64` if they have macOS Catalina, and I'll document this in the README. The default value will remain `i386;x86_64` for so long as there are still users with older macOS versions floating around.

**Comment by mphoward** [comment]
Resolved by PR #5
