### ISSUE TITLE
GSD 2.0 support

### ISSUE THREAD

**Issue by joaander** [mphoward/gsd-vmd#4]
GSD 2.0 will be released next week. It introduces breaking changes to the file format to enable longer chunk names and better performance when reading and writing many small chunks which will be common in HOOMD v3.0. GSD 2.0 can read and write to GSD 1.0 files, but GSD 1.0 cannot read GSD 2.0 files.

The GSD 2.0 code is complete. Feel free to copy `gsd.h` and `gsd.c` from the gsd master branch to enable support for 2.0 files before the official release is tagged. The C API only introduces one breaking change: The meaning of the function return values differ from 1.x. All C API functions now return the same error codes which are labelled with the `gsd_error` enum: https://gsd.readthedocs.io/en/latest/changes.html

HOOMD-blue will start writing GSD 2.0 files with the 2.9 release: https://github.com/glotzerlab/hoomd-blue/issues/578 .

**Comment by mphoward** [comment]
Thanks for the heads up! I will update these here. Will the HOOMD schema version stay the same when bumping to GSD 2.0?

**Comment by joaander** [comment]
Yes the HOOMD schema remains the same.

**Comment by mphoward** [comment]
Resolved by PR #5
